api_version = "2025-07"

[[extensions]]
name = "t:name"
handle = "wrapify"
type = "function"
uid = "0665236b-2116-28b4-ccc8-4c40f046e1df5adf93bd"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
